use GD2C2023
go

-- DROP TABLAS

-- DROP PROCEDURES

-- DROP VISTAS

-- CREACION DE SCHEMA
if exists (select name from sys.schemas where name = 'LOS_QUERY_EXPLORERS_BI')
    drop schema LOS_QUERY_EXPLORERS_BI;
go

create schema LOS_QUERY_EXPLORERS_BI;
go

-- CREACION DE TABLAS

-- CREACION DE PK

-- CREACION DE FK

-- CREACION PROCEDURE MIGRACION

-- EJECUCIONES DE PROCEDURES

-- CREACION DE VISTAS